Get http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "id": 1,
  "content": "HTML is easy",
  "date": "2022-01-10T17:30:31.098Z",
  "important": true
}